name: CD

variables:
- name: PACKAGE_USER
  value: ultimaker
- name: PACKAGE_CHANNEL
  value: testing

trigger:
  branches:
    include:
      - main
      - master
      - releases/*
      - refs/tags/v*

pr:
  - main
  - releases/*

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - bash: |
          pip install conan
          conan config install https://github.com/ultimaker/conan-config.git
          conan profile new default --detect
          conan user -p $MAPPED_CONAN_PASS -r ultimaker $MAPPED_CONAN_USER
        displayName: Prepare Conan environment
        env:
          MAPPED_CONAN_USER: $(CONAN_USER)
          MAPPED_CONAN_PASS: $(CONAN_PASS)
      - bash: python scripts/export_all.py $(PACKAGE_USER) $(PACKAGE_CHANNEL)
        displayName: Export all Conan packages
      - bash: conan upload "*" -r ultimaker --all -c
        displayName: Upload Conan package(s)
