name: conan-package-export

on:
  push:
    paths:
      - 'recipes/**'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'

permissions:
  contents: read

jobs:
  conan-package-export:
    name: Conan Package Export

    runs-on: ubuntu-latest
    steps:
# FIXME: use main once merged
      - name: Setup the build environment
        uses: ultimaker/cura-workflows/.github/actions/setup-build-environment@CURA-11622_conan_v2
        with:
          conan_user: ${{ secrets.CONAN_USER }}
          conan_password: ${{ secrets.CONAN_PASS }}

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            recipes/**/*.*

      - name: Export changed recipes
        run: |
          python Cura-workflows/runner_scripts/upload_conan_recipes.py --user ultimaker --branch ${{ github.ref_name }} --remote cura-conan2-dev ${{ env.GIT_DIFF_FILTERED }}
